import { log } from "console";
import { GetServerSidePropsContext } from "next";
import Head from "next/head";

type Product = {
      id: 2,
      title: 'Mens Casual Premium Slim Fit T-Shirts ',
      price: 22.3,
      description: 'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.',
      category: "men's clothing",
      image: 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg',
      rating: [Object]
}
type Props = {
  products: Product[]
}
export default function Home({products}: Props) {
  return (
  /* Esto se ejecuta del lado del (cliente) navegador y es para mostrar en la pantalla los datos obtenidos de la API*/
    <>
      <Head>
        <title>eCommerce Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ol>
        {products.map(product => {
          return <li key={product.id}>{product.title}</li>
        })}
        </ol>
      </main>
    </>
  )
}

/* Esto se ejecuta del lado del servidor y es para obtener los datos de la API*/
export async function getServerSideProps(context: GetServerSidePropsContext) {
  const products = await fetch('https://fakestoreapi.com/products')
  .then((res) => res.json())

  return {
    props: {
      products
    }
  }
}
